#!/usr/bin/python
import os

# Extract the features
image_path = "../data/dataset/train/data/"
image_test_path = "../data/dataset/test/data/"
data_path = "../data/dataset/train/features/"
data_test_path = "../data/dataset/test/features/"
# model_path = "../data/dataset/modelcomplete/"
video_path = "../data/dataset/datasample1.mov"

#Extraction
os.system("python ../object-detector/extract-features.py -i   {} -d {}".format(image_path, data_path))
# os.system("python ../object-detector/extract-features.py -i {} -d {}".format(image_test_path, data_test_path))
#os.system("python ../object-detector/load-features.py -d {}".format(data_path))

# Train the Model
os.system("python ../object-detector/train-classifier.py -d {}".format(data_path))

# Test the Model
# os.system("python ../object-detector/test-object.py -d {}".format(data_test_path))

# Run the video
#os.system("python ../object-detector/backgroud.py {}".format(video_path))
# # Perform testing
# test_im_path = "../data/dataset/Autorickshaw/917.png"
# #test_im_path = "../data/dataset/out017.jpg"
# os.system("python ../object-detector/test-object.py -i {} --visualize".format(test_im_path))
